### PR TITLE
Add option for subscribing to the injector lambda

### PR DESCRIPTION
**Pull request by amuslija**
# Description

Add the security headers injector lambda as a `origin-response` event to the deployed CloudFront Distribution

### CODE REVIEW

**Comment by amuslija** [comment]
Hey @martrik, do you know how we publish this package? The version on `npm` and the version in `package.json` are not the same.

**Comment by martrik** [comment]
> Hey @martrik, do you know how we publish this package? The version on `npm` and the version in `package.json` are not the same.

Durga was keeping this branch `https://github.com/AulaEducation/website/tree/publish-releases` to release new version I think. Is the package.json version in there match the one in NPM?

**Comment by amuslija** [comment]
Yes it is!

**Comment by martrik** [comment]
I don't really remember why we have that separate branch, I think that it was just in case we were able to get some PR through to the original repo. That doesn't seem to be happening so we could just merge it to master.

**Pull request closed without merging**
